/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import acciones.Accion;
import com.sun.awt.AWTUtilities;
import java.awt.Container;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JFrame;

/**
 *
 * @author joseMiguelMurcia
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form PanelPersonalizado
     */
    private static JFrame ventana;
    private static Container panel;
    private static Accion acciones;
    
    /**
     * Constructor de la ventana
     * Recibimos por parámetro el marco contenedor
     * @param contenedor 
     */
    public Ventana(Container contenedor) {        
        panel = contenedor;
        setUndecorated(true);
        initComponents();
        iniciar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setBounds(new java.awt.Rectangle(0, 0, 250, 40));
        setMinimumSize(new java.awt.Dimension(250, 40));
        setName("aviso"); // NOI18N

        etiqueta.setBackground(java.awt.SystemColor.desktop);
        etiqueta.setFont(new java.awt.Font("Lucida Sans Typewriter", 1, 10)); // NOI18N
        etiqueta.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta.setText("hola");
        etiqueta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        etiqueta.setMaximumSize(new java.awt.Dimension(250, 40));
        etiqueta.setMinimumSize(new java.awt.Dimension(250, 40));
        etiqueta.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiqueta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        //evito que al cerrarse se cierre la aplicacion.
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setSize(250, 50);
        this.setOpacity(0.80f);
        this.setResizable(false);  
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().getWidth(),
        this.getBounds().getHeight(),30,30);    
        
        AWTUtilities.setWindowShape(this, forma);
        ventana = this;
    }

    public void ponerTexto(String entrada) {       
        etiqueta.setText(entrada); //To change body of generated methods, choose Tools | Templates.
    }
    
   
    public JFrame devolverVentana(){
        return this.ventana;
    }
    
    /**
     * Método que llama a realizar una accion en hilo aparte.
     * @param ventana 
     */
    /**
     * método que anima la ventana
     * 
     * La va a mover en un tamaño mínimo y máximo
     */
    public void animarVentana(JFrame ventana){        
        acciones = new Accion(panel,ventana);
        acciones.setDaemon(true);
        acciones.start();
    }
    
    
    

    
}//..Ventana()
